apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo
  description: An example deployment of a Backstage application.
  annotations:
    github.com/project-slug:  IanLeonOlivier/demoNew
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
spec:
  type: website
  owner: guests
  lifecycle: unknown
